analyzer:
  exclude:
    - test/mock_packages/**

linter:
  rules:
    - empty_constructor_bodies # pedantic
    - empty_statements
    - prefer_equal_for_default_values # pedantic
    - prefer_is_empty # pedantic
    - prefer_is_not_empty # pedantic
    - unnecessary_brace_in_string_interps
    - valid_regexps # pedantic
