include: package:pedantic/analysis_options.1.8.0.yaml

analyzer:
  # This currently finds ~4,500 implicit-casts issues when enabled.
  # strong-mode:
  #   implicit-casts: false
  errors:
    # Increase the severity of the unused_import hint.
    unused_import: warning
    # Ignoring "style" lint rules from pedantic for now. There are pre-existing
    # violations that need to be cleaned up. Each one can be cleaned up and
    # enabled according to the value provided.
    # TODO(srawlins): At the time of writing, 2600 violations in lib/. The fix
    # is mechanical, via `dartfmt --fix-doc-comments`, but not worth the churn
    # today.
    slash_for_doc_comments: ignore

linter:
  rules:
    - empty_statements
    - unnecessary_brace_in_string_interps
